apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-app-deployment
spec:
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle-app
        image: muralisocial123/oracle-web-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

